### ISSUE TITLE
Unable to change streaming resolution

### ISSUE THREAD

**Issue by arumugam666** [Parrot-Developers/olympe#10]
When using self.drone(set_recording_mode(0,0,0,0,0)).wait() to set the streaming resolution i run into:
Traceback (most recent call last):
  File "/home/arumugam/code/parrot-groundsdk/packages/olympe/src/olympe/_private/pomp_loop_thread.py", line 211, in _run_task_list
    ret = f(*args, **kwargs)
  File "/home/arumugam/code/parrot-groundsdk/packages/olympe/src/olympe/arsdkng/drone.py", line 871, in _send_command_impl
    raise RuntimeError("[sendcmd] Error cmd interface seems to be destroyed")
RuntimeError: [sendcmd] Error cmd interface seems to be destroyed

I want to set the resolution to 4k from the standard 1280x720

Thanks in advance!

**Comment by ndessart** [comment]
This particular error means that you are not connected to the drone and still trying to send a command message. What is the returned value of `drone.connection()` ?

**Comment by arumugam666** [comment]
I was connecting to the drone later, so that fixed it
