### ISSUE TITLE
    import ulog ModuleNotFoundError: No module named 'ulog'

### ISSUE THREAD

**Issue by ning-cs** [Parrot-Developers/olympe#22]
i have installed olympe flowing the guide[https://developer.parrot.com/docs/olympe/installation.html]
after ` ./products/olympe/linux/env/postinst`.
it occours error
`**ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.

We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.

sphinx-substitution-extensions 2018.11.12.3 requires sphinx==1.8.2, but you'll have sphinx 1.8.5 which is incompatible.**
`
then,i ignore the error,begin to check my installation,anathor eeror
`(olympe-python3) new@new:~/0.Workspace/code/parrot-groundsdk$  pip --version
pip 20.2.4 from /home/new/0.Workspace/code/parrot-groundsdk/.python/py3/lib/python3.6/site-packages/pip (python 3.6)
(olympe-python3) new@new:~/0.Workspace/code/parrot-groundsdk$ python -c 'import olympe; print("Installation OK")'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/new/0.Workspace/code/parrot-groundsdk/packages/olympe/src/olympe/__init__.py", line 6, in <module>
    import olympe.log
  File "/home/new/0.Workspace/code/parrot-groundsdk/packages/olympe/src/olympe/log/__init__.py", line 7, in <module>
    import ulog
**ModuleNotFoundError: No module named 'ulog'**
`
how could i fix it? Thanks!

**Comment by iaamp** [comment]
This issue seems to still exist. It is just a missing dependency though, and can be fixed via:
`pip install ulog`

**Comment by BjarneDesmetBrainJam** [comment]
Hi,

I have the same issue.
Installing ulog with pip does fix the problem but I get this error when executing:

AttributeError: module 'ulog' has no attribute 'enable_bridge'

Do you know if a certain version needs to be installed?

Thanks in advance!!

**Comment by manupollak** [comment]
Hi,

i have the same problem. Have you already found a solution?

Thanks
Manuela

**Comment by ndessart** [comment]
Have  you been able to reproduce this issue lately with the latest 7.X releases ? (currently the 7.4.2?)

**Comment by iaamp** [comment]
At least for me, the issue seems to be fixed. Tested with Olympe 7.2.0, which was installed via `pip parrot-olympe` within a Python 3 (v.3.8.10) virtualenv on Ubuntu 20.04.

If i remember correctly, the issue occurred back when Olympe was relying on an install shell script, instead of a Python wheel.
