### ISSUE TITLE
Unable to build from source: analyze_wheel_abi() missing arguments

### ISSUE THREAD

**Issue by achanana** [Parrot-Developers/olympe#55]
Hi folks,

I see the following compilation error when trying to build from source:
```
PythonWheel: olympe-wheel => Building...
/home/ubuntu/code-old/olympe/build/alchemy/scripts/wheel.py:53: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
Unhandled exception
Traceback (most recent call last):
  File "/home/ubuntu/code-old/olympe/build/alchemy/scripts/wheel.py", line 1100, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/home/ubuntu/code-old/olympe/build/alchemy/scripts/wheel.py", line 1094, in main
    builder.build()
  File "/home/ubuntu/code-old/olympe/build/alchemy/scripts/wheel.py", line 888, in build
    wheel_info = analyze_wheel(wheel_path)
  File "/home/ubuntu/code-old/olympe/build/alchemy/scripts/wheel.py", line 159, in analyze_wheel
    wheel_info = analyze_wheel_abi(str(wheel_path))
TypeError: analyze_wheel_abi() missing 2 required positional arguments: 'wheel_fn' and 'exclude'
make: *** [/home/ubuntu/code-old/olympe/build/alchemy/classes/PYTHON_WHEEL/rules.mk:39: /home/ubuntu/code-old/olympe/out/olympe-linux/build/olympe-wheel/parrot-olympe.whl] Error 1
```
I see this error when building both for ARM and x86. Seems like a newer wheel package is in use that expects more arguments than are provided. Is there a workaround for this? I couldn't find where a package version can be specified for this package.

I have tried building v7.7.4 and v7.6.0—both cause this compilation error. I tried building on Ubuntu 20.04.

Thanks for your help!

**Comment by ndessart** [comment]
This should be fixed in [v7.7.5](https://github.com/Parrot-Developers/olympe/releases/tag/v7.7.5).
Please tell me if that works for you. Thank you
