### ISSUE TITLE
Log

### ISSUE THREAD

**Issue by shulace13** [Parrot-Developers/olympe#6]
When executing the scripts, I get a ton of logs. Is this normal and is there a way to disable this? It is nice to see what's happening but it is hard to check if the script itself is working well or not.
Here is an example from takeoff.py
```
01/07/2019 12:14:49.522965	_create_pomp_loop               Creating pomp loop
01/07/2019 12:14:49.523848	_create_manager                 New manager has been created!
01/07/2019 12:14:49.524267	_create_manager                 Manager device callbacks has been added to the manager
01/07/2019 12:14:49.524821	_create_net_backend             New net backend has been created
01/07/2019 12:14:49.525252	_create_net_backend             Set backend socket callback OK
01/07/2019 12:14:49.525658	create_timer                    Creating pomp timer
01/07/2019 12:14:49.526095	create_timer                    Creating pomp timer
01/07/2019 12:14:49.528232	_start_net_discovery            Net discovery object has been created
I arsdkctrl: discovery 'net': start
01/07/2019 12:14:49.529062	_backend_socket_cb              backend_pointer <olympe_deps.LP_struct_arsdkctrl_backend_net object at 0x7efe6d775f28> socket_fd 10 socket_kind 0 userdate_pointer None
01/07/2019 12:14:49.529779	_start_net_discovery            Net discovery has been started
I arsdkctrl: discovery 'net': add device name='ANAFI-0000000' id='000000000000000000'
01/07/2019 12:14:49.531901	_device_added_cb                New device has been detected
01/07/2019 12:14:49.532621	_device_added_cb                {'state': 0}
01/07/2019 12:14:49.533782	_backend_socket_cb              backend_pointer <olympe_deps.LP_struct_arsdkctrl_backend_net object at 0x7efe6d74dae8> socket_fd 13 socket_kind 2 userdate_pointer None
01/07/2019 12:14:49.534660	_backend_socket_cb              backend_pointer <olympe_deps.LP_struct_arsdkctrl_backend_net object at 0x7efe6d74dae8> socket_fd 14 socket_kind 1 userdate_pointer None
01/07/2019 12:14:49.535703	_connecting_cb                  Connecting to device: ANAFI-0000000
01/07/2019 12:14:49.536395	_connect_to_device              Connection in progress...
I arsdkctrl_net: Sending json:
I arsdkctrl_net: { "arstream2_client_stream_port": "55004", "arstream2_client_control_port": "55005", "arstream2_supported_metadata_version": "1", "controller_name": "arsdk-ng", "controller_type": "desktop", "d2c_port": 9988, "device_id": "", "qos_mode": 0 }
I arsdkctrl_net: Received json:
I arsdkctrl_net: { "c2d_update_port": 51, "c2d_user_port": 21, "status": 0, "c2d_port": 2233, "qos_mode": 0 }
01/07/2019 12:14:49.537632	_connected_cb                   Connected to device: ANAFI-0000000
01/07/2019 12:14:49.538766	_connected_cb                   {'json': {'c2d_port': 2233,
          'c2d_update_port': 51,
          'c2d_user_port': 21,
          'qos_mode': 0,
          'status': 0},
 'state': 0}
01/07/2019 12:14:49.540207	_create_command_interface       Command interface has been created: itf=<olympe_deps.LP_struct_arsdk_cmd_itf object at 0x7efe6d74d950>
I pdraw_session: state change to CREATED
01/07/2019 12:14:49.542878	__init__                        Pdraw interface has been created
01/07/2019 12:14:49.579537	_recv_cmd_cb                    common.ARLibsVersionsState.DeviceLibARCommandsVersion(version='4.0.0.4')
01/07/2019 12:14:49.580571	_recv_cmd_cb                    common.CommonState.BatteryStateChanged(percent=99)
01/07/2019 12:14:49.581590	_recv_cmd_cb                    common.CommonState.BootId(bootId='EA19E8798A30D5434E84BCC6840421A6')
01/07/2019 12:14:49.582846	_recv_cmd_cb                    common.CalibrationState.MagnetoCalibrationRequiredState(required=0)
01/07/2019 12:14:49.583764	_recv_cmd_cb                    ardrone3.PilotingState.AlertStateChanged(state=AlertStateChanged_State.none)
01/07/2019 12:14:49.584707	_recv_cmd_cb                    common.CommonState.SensorsStatesListChanged(sensorName=SensorsStatesListChanged_SensorName.IMU, sensorState=1)
01/07/2019 12:14:49.585647	_recv_cmd_cb                    common.CommonState.SensorsStatesListChanged(sensorName=SensorsStatesListChanged_SensorName.magnetometer, sensorState=1)
01/07/2019 12:14:49.586617	_recv_cmd_cb                    common.CommonState.SensorsStatesListChanged(sensorName=SensorsStatesListChanged_SensorName.barometer, sensorState=1)
01/07/2019 12:14:49.587537	_recv_cmd_cb                    common.CommonState.SensorsStatesListChanged(sensorName=SensorsStatesListChanged_SensorName.GPS, sensorState=1)
01/07/2019 12:14:49.588468	_recv_cmd_cb                    common.CommonState.SensorsStatesListChanged(sensorName=SensorsStatesListChanged_SensorName.ultrasound, sensorState=1)
01/07/2019 12:14:49.589463	_recv_cmd_cb                    common.CommonState.SensorsStatesListChanged(sensorName=SensorsStatesListChanged_SensorName.vertical_camera, sensorState=1)
01/07/2019 12:14:49.590523	_recv_cmd_cb                    battery.alert(alert=alert.power_level, level=alert_level.none, list_flags='First')
01/07/2019 12:14:49.591495	_recv_cmd_cb                    battery.alert(alert=alert.too_hot, level=alert_level.none, list_flags='')
01/07/2019 12:14:49.592455	_recv_cmd_cb                    battery.alert(alert=alert.too_cold, level=alert_level.none, list_flags='Last')
01/07/2019 12:14:49.593393	_recv_cmd_cb                    battery.health(state_of_health=100)
01/07/2019 12:14:49.594302	_recv_cmd_cb                    ardrone3.GPSSettingsState.GPSFixStateChanged(fixed=1)
01/07/2019 12:14:49.595199	_recv_cmd_cb                    ardrone3.GPSState.NumberOfSatelliteChanged(numberOfSatellite=12)
01/07/2019 12:14:49.596109	_recv_cmd_cb                    ardrone3.SettingsState.MotorSoftwareVersionChanged(version='0.1.x.4')
01/07/2019 12:14:49.597082	_recv_cmd_cb                    ardrone3.SettingsState.MotorErrorStateChanged(motorIds=15, motorError=MotorErrorStateChanged_MotorError.noError)
01/07/2019 12:14:49.598019	_recv_cmd_cb                    ardrone3.SettingsState.MotorFlightsStatusChanged(nbFlights=0, lastFlightDuration=0, totalFlightDuration=0)
01/07/2019 12:14:49.598931	_recv_cmd_cb                    ardrone3.SettingsState.MotorErrorLastErrorChanged(motorError=MotorErrorLastErrorChanged_MotorError.noError)
01/07/2019 12:14:49.599934	_recv_cmd_cb                    user_storage.state(physical_state=phy_state.undetected, file_system_state=fs_state.unknown, attribute='', monitor_enabled=0, monitor_period=0)
01/07/2019 12:14:49.600863	_recv_cmd_cb                    user_storage.info(name='', capacity=0)
01/07/2019 12:14:49.601812	_recv_cmd_cb                    user_storage.capabilities(supported_features='format_when_ready_allowed|format_result_evt_supported|format_progress_evt_supported')
01/07/2019 12:14:49.602761	_recv_cmd_cb                    user_storage.supported_formatting_types(supported_types='full|quick')
01/07/2019 12:14:49.605443	_recv_cmd_cb                    common.CalibrationState.MagnetoCalibrationStartedChanged(started=0)
01/07/2019 12:14:49.606638	_recv_cmd_cb                    ardrone3.PilotingState.NavigateHomeStateChanged(state=NavigateHomeStateChanged_State.unavailable, reason=NavigateHomeStateChanged_Reason.userRequest)
01/07/2019 12:14:49.607924	_recv_cmd_cb                    ardrone3.GPSState.HomeTypeAvailabilityChanged(type=HomeTypeAvailabilityChanged_Type.TAKEOFF, available=0)
01/07/2019 12:14:49.608850	_recv_cmd_cb                    ardrone3.GPSState.HomeTypeAvailabilityChanged(type=HomeTypeAvailabilityChanged_Type.PILOT, available=0)
01/07/2019 12:14:49.609800	_recv_cmd_cb                    ardrone3.GPSState.HomeTypeAvailabilityChanged(type=HomeTypeAvailabilityChanged_Type.FIRST_FIX, available=4)
01/07/2019 12:14:49.610789	_recv_cmd_cb                    ardrone3.GPSState.HomeTypeAvailabilityChanged(type=HomeTypeAvailabilityChanged_Type.FOLLOWEE, available=0)
01/07/2019 12:14:49.611719	_recv_cmd_cb                    ardrone3.GPSState.HomeTypeChosenChanged(type=HomeTypeChosenChanged_Type.FIRST_FIX)
01/07/2019 12:14:49.612653	_recv_cmd_cb                    rth.home_reachability(status=home_reachability.unknown)
01/07/2019 12:14:49.613607	_recv_cmd_cb                    rth.rth_auto_trigger(reason=auto_trigger_reason.none, delay=0)
01/07/2019 12:14:49.614540	_recv_cmd_cb                    ardrone3.PilotingState.ForcedLandingAutoTrigger(reason=ForcedLandingAutoTrigger_Reason.NONE, delay=0)
01/07/2019 12:14:49.615468	_recv_cmd_cb                    ardrone3.PilotingState.WindStateChanged(state=WindStateChanged_State.ok)
01/07/2019 12:14:49.616429	_recv_cmd_cb                    common.MavlinkState.MavlinkFilePlayingStateChanged(state=MavlinkFilePlayingStateChanged_State.stopped, filepath='', type=MavlinkFilePlayingStateChanged_Type.flightPlan)
01/07/2019 12:14:49.617404	_recv_cmd_cb                    common.FlightPlanState.ComponentStateListChanged(component=ComponentStateListChanged_Component.GPS, State=1)
01/07/2019 12:14:49.618347	_recv_cmd_cb                    common.FlightPlanState.ComponentStateListChanged(component=ComponentStateListChanged_Component.Calibration, State=1)
01/07/2019 12:14:49.619287	_recv_cmd_cb                    common.FlightPlanState.ComponentStateListChanged(component=ComponentStateListChanged_Component.TakeOff, State=1)
01/07/2019 12:14:49.620198	_recv_cmd_cb                    common.FlightPlanState.AvailabilityStateChanged(AvailabilityState=1)
01/07/2019 12:14:49.621328	_recv_cmd_cb                    follow_me.state(mode=mode.none, behavior=behavior.idle, animation=animation.none, animation_available='')
01/07/2019 12:14:49.622297	_recv_cmd_cb                    follow_me.target_framing_position_changed(horizontal=0, vertical=0)
01/07/2019 12:14:49.623273	_recv_cmd_cb                    follow_me.target_image_detection_state(state=image_detection_status.none)
01/07/2019 12:14:49.624387	_recv_cmd_cb                    follow_me.mode_info(mode=mode.look_at, missing_requirements='drone_calibrated|drone_gps_good_accuracy|target_gps_good_accuracy|target_barometer_ok|drone_far_enough|drone_high_enough', improvements='drone_calibrated|drone_gps_good_accuracy|target_gps_good_accuracy|target_barometer_ok|drone_far_enough|drone_high_enough|image_detection')
01/07/2019 12:14:49.625475	_recv_cmd_cb                    follow_me.mode_info(mode=mode.geographic, missing_requirements='target_barometer_ok|drone_far_enough|drone_high_enough', improvements='drone_calibrated|drone_gps_good_accuracy|target_gps_good_accuracy|target_barometer_ok|drone_far_enough|drone_high_enough|image_detection')
01/07/2019 12:14:49.626543	_recv_cmd_cb                    follow_me.mode_info(mode=mode.relative, missing_requirements='target_barometer_ok|drone_far_enough|drone_high_enough', improvements='drone_calibrated|drone_gps_good_accuracy|target_gps_good_accuracy|target_barometer_ok|drone_far_enough|drone_high_enough|image_detection')
01/07/2019 12:14:49.627638	_recv_cmd_cb                    follow_me.mode_info(mode=mode.leash, missing_requirements='target_barometer_ok|drone_far_enough|drone_high_enough', improvements='drone_calibrated|drone_gps_good_accuracy|target_gps_good_accuracy|target_barometer_ok|drone_far_enough|drone_high_enough|image_detection')
01/07/2019 12:14:49.628558	_recv_cmd_cb                    follow_me.target_is_controller(state=0)
01/07/2019 12:14:49.629955	_recv_cmd_cb                    ardrone3.SoundState.AlertSound(state=AlertSound_State.stopped)
01/07/2019 12:14:49.630930	_recv_cmd_cb                    mediastore.state(state=state.indexed)
01/07/2019 12:14:49.631930	_recv_cmd_cb                    mediastore.counters(video_media_count=0, photo_media_count=0, video_resource_count=0, photo_resource_count=0)
01/07/2019 12:14:49.632898	_recv_cmd_cb                    ardrone3.PilotingState.HoveringWarning(no_gps_too_dark=0, no_gps_too_high=0)
01/07/2019 12:14:49.633906	_recv_cmd_cb                    camera.camera_mode(cam_id=0, mode=camera_mode.recording)
01/07/2019 12:14:49.634890	_recv_cmd_cb                    camera.hdr_setting(cam_id=0, value=state.inactive)
01/07/2019 12:14:49.635862	_recv_cmd_cb                    camera.hdr(cam_id=0, available=availability.not_available, state=state.inactive)
01/07/2019 12:14:49.636929	_recv_cmd_cb                    camera.photo_mode(cam_id=0, mode=photo_mode.single, format=photo_format.full_frame, file_format=photo_file_format.jpeg, burst=burst_value.burst_14_over_1s, bracketing=bracketing_preset.preset_1ev, capture_interval=0.0)
01/07/2019 12:14:49.637974	_recv_cmd_cb                    camera.recording_mode(cam_id=0, mode=recording_mode.standard, resolution=resolution.res_uhd_4k, framerate=framerate.fps_30, hyperlapse=hyperlapse_value.ratio_15, bitrate=10000000)
01/07/2019 12:14:49.638969	_recv_cmd_cb                    camera.white_balance(cam_id=0, mode=white_balance_mode.automatic, temperature=white_balance_temperature.t_1500, lock=state.inactive)
01/07/2019 12:14:49.640234	_recv_cmd_cb                    camera.exposure_settings(cam_id=0, mode=exposure_mode.automatic, manual_shutter_speed=shutter_speed.shutter_1_over_10000, manual_shutter_speed_capabilities='shutter_1_over_10000|shutter_1_over_8000|shutter_1_over_6400|shutter_1_over_5000|shutter_1_over_4000|shutter_1_over_3200|shutter_1_over_2500|shutter_1_over_2000|shutter_1_over_1600|shutter_1_over_1250|shutter_1_over_1000|shutter_1_over_800|shutter_1_over_640|shutter_1_over_500|shutter_1_over_400|shutter_1_over_320|shutter_1_over_240|shutter_1_over_200|shutter_1_over_160|shutter_1_over_120|shutter_1_over_100|shutter_1_over_80|shutter_1_over_60|shutter_1_over_50|shutter_1_over_40|shutter_1_over_30', manual_iso_sensitivity=iso_sensitivity.iso_50, manual_iso_sensitivity_capabilities='iso_100|iso_160|iso_200|iso_320|iso_400|iso_640|iso_800|iso_1200|iso_1600|iso_2500|iso_3200', max_iso_sensitivity=iso_sensitivity.iso_3200, max_iso_sensitivities_capabilities='iso_3200')
01/07/2019 12:14:49.641211	_recv_cmd_cb                    camera.ev_compensation(cam_id=0, value=ev_compensation.ev_0_00)
01/07/2019 12:14:49.642291	_recv_cmd_cb                    camera.style(cam_id=0, style=style.standard, saturation=0, saturation_min=-2, saturation_max=2, contrast=0, contrast_min=-2, contrast_max=2, sharpness=0, sharpness_min=-1, sharpness_max=1)
01/07/2019 12:14:49.643269	_recv_cmd_cb                    camera.recording_state(cam_id=0, available=availability.available, state=state.inactive, start_timestamp=0)
01/07/2019 12:14:49.644227	_recv_cmd_cb                    ardrone3.MediaRecordState.VideoStateChangedV2(state=VideoStateChangedV2_State.stopped, error=VideoStateChangedV2_Error.ok)
01/07/2019 12:14:49.645188	_recv_cmd_cb                    camera.photo_state(cam_id=0, available=availability.not_available, state=state.inactive)
01/07/2019 12:14:49.646132	_recv_cmd_cb                    camera.antiflicker_mode(mode=antiflicker_mode.mode_50hz, value=antiflicker_mode.mode_50hz)
01/07/2019 12:14:49.647046	_recv_cmd_cb                    thermal.mode(mode=mode.disabled)
01/07/2019 12:14:49.648085	_recv_cmd_cb                    thermal.palette_settings(mode=palette_mode.absolute, lowest_temp=0.0, highest_temp=0.0, outside_colorization=colorization_mode.limited, relative_range=relative_range_mode.locked, spot_type=spot_type.cold, spot_threshold=0.0)
01/07/2019 12:14:49.649031	_recv_cmd_cb                    thermal.rendering(mode=rendering_mode.visible, blending_rate=0.0)
01/07/2019 12:14:49.649941	_recv_cmd_cb                    thermal.emissivity(emissivity=0.0)
01/07/2019 12:14:49.650837	_recv_cmd_cb                    thermal.background_temperature(background_temperature=0.0)
01/07/2019 12:14:49.651750	_recv_cmd_cb                    thermal.sensitivity(current_range=range.low)
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "/home/shu18/parrot-groundsdk/out/olympe-linux/final/usr/lib/python/site-packages/olympe_deps.py", line 42, in <lambda>
    type_((lambda callback: lambda *args: callback(*args))(bound_fields[name]))
  File "/home/shu18/parrot-groundsdk/packages/olympe/src/olympe/arsdkng/drone.py", line 406, in _recv_cmd_cb
    raise RuntimeError("Unknown message id {}".format(message_id))
RuntimeError: Unknown message id 2550136849
01/07/2019 12:14:49.653666	_recv_cmd_cb                    camera.camera_states(active_cameras=1)
01/07/2019 12:14:49.654627	_recv_cmd_cb                    camera.zoom_info(cam_id=0, available=availability.available, high_quality_maximum_level=1.4000070095062256, maximum_level=2.9999840259552)
01/07/2019 12:14:49.655572	_recv_cmd_cb                    gimbal.axis_lock_state(gimbal_id=0, locked='')
01/07/2019 12:14:49.656500	_recv_cmd_cb                    gimbal.alert(gimbal_id=0, error='')
01/07/2019 12:14:49.657431	_recv_cmd_cb                    animation.availability(values='')
01/07/2019 12:14:49.658374	_recv_cmd_cb                    animation.state(type=type.none, percent=0)
01/07/2019 12:14:49.659276	_recv_cmd_cb                    common.SettingsState.BoardIdChanged(id='0x0')
01/07/2019 12:14:49.660193	_recv_cmd_cb                    precise_home.mode(mode=mode.disabled)
01/07/2019 12:14:49.661123	_recv_cmd_cb                    precise_home.state(state=state.unavailable)
01/07/2019 12:14:49.662056	_recv_cmd_cb                    precise_home.capabilities(modes='disabled|standard')
01/07/2019 12:14:49.662928	_recv_cmd_cb                    common.CommonState.AllStatesChanged()
01/07/2019 12:14:49.663769	_send_command                   Common.Common.AllStates(): sent and acknowledged
01/07/2019 12:14:49.665698	_recv_cmd_cb                    common.SettingsState.ProductSerialHighChanged(high='000000000')
01/07/2019 12:14:49.666599	_recv_cmd_cb                    common.SettingsState.ProductSerialLowChanged(low='000000000')
01/07/2019 12:14:49.667518	_recv_cmd_cb                    common.SettingsState.ProductVersionChanged(software='1.5.6', hardware='HW_00')
01/07/2019 12:14:49.668975	_recv_cmd_cb                    camera.camera_capabilities(cam_id=0, model=model.main, exposure_modes='automatic|automatic_prefer_iso_sensitivity|automatic_prefer_shutter_speed|manual_iso_sensitivity|manual_shutter_speed|manual', exposure_lock_supported=supported.supported, exposure_roi_lock_supported=supported.supported, ev_compensations='ev_minus_3_00|ev_minus_2_67|ev_minus_2_33|ev_minus_2_00|ev_minus_1_67|ev_minus_1_33|ev_minus_1_00|ev_minus_0_67|ev_minus_0_33|ev_0_00|ev_0_33|ev_0_67|ev_1_00|ev_1_33|ev_1_67|ev_2_00|ev_2_33|ev_2_67|ev_3_00', white_balance_modes='automatic|incandescent|fluorescent|cool_white_fluorescent|sunny|cloudy|green_foliage|blue_sky', custom_white_balance_temperatures='', white_balance_lock_supported=supported.supported, styles='standard|plog', camera_modes='recording|photo', hyperlapse_values='', bracketing_presets='', burst_values='', streaming_modes='', timelapse_interval_min=0.0, gpslapse_interval_min=0.0)
01/07/2019 12:14:49.733440	_recv_cmd_cb                    camera.recording_capabilities(id=0, recording_modes='standard', resolutions='res_dci_4k', framerates='fps_24', hdr=supported.supported, list_flags='First')
01/07/2019 12:14:49.734787	_recv_cmd_cb                    camera.recording_capabilities(id=1, recording_modes='standard|hyperlapse', resolutions='res_uhd_4k|res_2_7k|res_1080p', framerates='fps_24|fps_25|fps_30|fps_9', hdr=supported.supported, list_flags='')
01/07/2019 12:14:49.735917	_recv_cmd_cb                    camera.recording_capabilities(id=2, recording_modes='slow_motion|high_framerate', resolutions='res_1080p|res_720p|res_1080p_sd', framerates='fps_48|fps_50|fps_60', hdr=supported.not_supported, list_flags='')
01/07/2019 12:14:49.736975	_recv_cmd_cb                    camera.recording_capabilities(id=3, recording_modes='slow_motion|high_framerate', resolutions='res_720p', framerates='', hdr=supported.not_supported, list_flags='Last')
01/07/2019 12:14:49.738079	_recv_cmd_cb                    camera.photo_capabilities(id=0, photo_modes='single|time_lapse|gps_lapse', photo_formats='full_frame', photo_file_formats='dng_jpeg', hdr=supported.supported, list_flags='First')
01/07/2019 12:14:49.739141	_recv_cmd_cb                    camera.photo_capabilities(id=1, photo_modes='single|burst|time_lapse|gps_lapse', photo_formats='full_frame', photo_file_formats='jpeg', hdr=supported.supported, list_flags='')
01/07/2019 12:14:49.740189	_recv_cmd_cb                    camera.photo_capabilities(id=2, photo_modes='single|burst|time_lapse|gps_lapse', photo_formats='rectilinear', photo_file_formats='jpeg', hdr=supported.supported, list_flags='')
01/07/2019 12:14:49.741263	_recv_cmd_cb                    camera.photo_capabilities(id=3, photo_modes='single|bracketing|time_lapse|gps_lapse', photo_formats='full_frame', photo_file_formats='dng_jpeg', hdr=supported.not_supported, list_flags='')
01/07/2019 12:14:49.742325	_recv_cmd_cb                    camera.photo_capabilities(id=4, photo_modes='single|bracketing|burst|time_lapse|gps_lapse', photo_formats='full_frame', photo_file_formats='jpeg', hdr=supported.not_supported, list_flags='')
01/07/2019 12:14:49.743395	_recv_cmd_cb                    camera.photo_capabilities(id=5, photo_modes='single|bracketing|burst|time_lapse|gps_lapse', photo_formats='rectilinear', photo_file_formats='jpeg', hdr=supported.not_supported, list_flags='Last')
01/07/2019 12:14:49.744363	_recv_cmd_cb                    camera.antiflicker_capabilities(supported_modes='off|mode_50hz|mode_60hz')
01/07/2019 12:14:49.745302	_recv_cmd_cb                    thermal.capabilities(modes='')
01/07/2019 12:14:49.746222	_recv_cmd_cb                    leds.capabilities(supported_capabilities='')
01/07/2019 12:14:49.747205	_recv_cmd_cb                    ardrone3.PilotingSettingsState.MaxAltitudeChanged(current=30.0, min=0.5, max=150.0)
01/07/2019 12:14:49.748133	_recv_cmd_cb                    ardrone3.PilotingSettingsState.MaxDistanceChanged(current=100.0, min=10.0, max=4000.0)
01/07/2019 12:14:49.749061	_recv_cmd_cb                    ardrone3.PilotingSettingsState.NoFlyOverMaxDistanceChanged(shouldNotFlyOver=0)
01/07/2019 12:14:49.749987	_recv_cmd_cb                    ardrone3.PilotingSettingsState.MaxTiltChanged(current=1.0, min=1.0, max=40.0)
01/07/2019 12:14:49.750919	_recv_cmd_cb                    ardrone3.SpeedSettingsState.MaxVerticalSpeedChanged(current=1.0, min=0.10000000149011612, max=4.0)
01/07/2019 12:14:49.751881	_recv_cmd_cb                    ardrone3.SpeedSettingsState.MaxRotationSpeedChanged(current=70.0, min=3.0, max=200.0)
01/07/2019 12:14:49.752822	_recv_cmd_cb                    ardrone3.SpeedSettingsState.MaxPitchRollRotationSpeedChanged(current=150.0, min=80.0, max=300.0)
01/07/2019 12:14:49.753744	_recv_cmd_cb                    ardrone3.PilotingSettingsState.BankedTurnChanged(state=0)
01/07/2019 12:14:49.754640	_recv_cmd_cb                    ardrone3.SpeedSettingsState.HullProtectionChanged(present=0)
01/07/2019 12:14:49.755538	_recv_cmd_cb                    ardrone3.GPSSettingsState.ReturnHomeDelayChanged(delay=60)
01/07/2019 12:14:49.756472	_recv_cmd_cb                    ardrone3.GPSSettingsState.ReturnHomeMinAltitudeChanged(value=20.0, min=20.0, max=100.0)
01/07/2019 12:14:49.757390	_recv_cmd_cb                    ardrone3.PilotingSettingsState.MotionDetection(enabled=0)
01/07/2019 12:14:49.758310	_recv_cmd_cb                    ardrone3.GPSSettingsState.HomeTypeChanged(type=HomeTypeChanged_Type.FOLLOWEE)
01/07/2019 12:14:49.759226	_recv_cmd_cb                    common.SettingsState.ProductNameChanged(name='Parrot Drone')
01/07/2019 12:14:49.760163	_recv_cmd_cb                    wifi.supported_security_types(types='open|wpa2')
01/07/2019 12:14:49.761144	_recv_cmd_cb                    wifi.security_changed(type=security_type.open, key='', key_type=security_key_type.plain)
01/07/2019 12:14:49.762094	_recv_cmd_cb                    wifi.ap_channel_changed(type=selection_type.auto_all, band=-1, channel=255)
01/07/2019 12:14:49.763025	_recv_cmd_cb                    wifi.country_changed(selection_mode=country_selection.auto, code='FR')
01/07/2019 12:14:49.763958	_recv_cmd_cb                    wifi.environment_changed(environment=environment.outdoor)
01/07/2019 12:14:49.764936	_recv_cmd_cb                    gimbal.gimbal_capabilities(gimbal_id=0, model=model.main, axes='pitch|roll')
01/07/2019 12:14:49.765937	_recv_cmd_cb                    gimbal.relative_attitude_bounds(gimbal_id=0, min_yaw=0.0, max_yaw=0.0, min_pitch=-135.0, max_pitch=105.0, min_roll=0.0, max_roll=0.0)
01/07/2019 12:14:49.766928	_recv_cmd_cb                    gimbal.absolute_attitude_bounds(gimbal_id=0, min_yaw=0.0, max_yaw=0.0, min_pitch=-90.0, max_pitch=90.0, min_roll=0.0, max_roll=0.0)
01/07/2019 12:14:49.767844	_recv_cmd_cb                    ardrone3.CameraState.VelocityRange(max_tilt=14.0, max_pan=0.0)
01/07/2019 12:14:49.768856	_recv_cmd_cb                    gimbal.max_speed(gimbal_id=0, min_bound_yaw=0.0, max_bound_yaw=0.0, current_yaw=0.0, min_bound_pitch=1.0, max_bound_pitch=180.0, current_pitch=14.0, min_bound_roll=0.0, max_bound_roll=0.0, current_roll=0.0)
01/07/2019 12:14:49.769793	_recv_cmd_cb                    ardrone3.CameraState.defaultCameraOrientationV2(tilt=0.0, pan=0.0)
01/07/2019 12:14:49.770741	_recv_cmd_cb                    camera.max_zoom_speed(cam_id=0, min=0.009999999776482582, max=10.0, current=0.3400000035762787)
01/07/2019 12:14:49.771672	_recv_cmd_cb                    camera.zoom_velocity_quality_degradation(cam_id=0, allowed=1)
01/07/2019 12:14:49.772613	_recv_cmd_cb                    gimbal.calibration_state(state=calibration_state.ok, gimbal_id=0)
01/07/2019 12:14:49.773668	_recv_cmd_cb                    gimbal.offsets(gimbal_id=0, update_state=state.inactive, min_bound_yaw=0.0, max_bound_yaw=0.0, current_yaw=3.0785125962751906e-41, min_bound_pitch=-5.0, max_bound_pitch=5.0, current_pitch=0.0, min_bound_roll=-5.0, max_bound_roll=5.0, current_roll=0.0)
01/07/2019 12:14:49.774618	_recv_cmd_cb                    camera.autorecord(cam_id=0, state=state.active)
01/07/2019 12:14:49.775533	_recv_cmd_cb                    ardrone3.SettingsState.ProductGPSVersionChanged(software='', hardware='')
01/07/2019 12:14:49.776422	_recv_cmd_cb                    common.SettingsState.AllSettingsChanged()
01/07/2019 12:14:49.777587	_send_command                   Common.Settings.AllSettings(): sent and acknowledged
01/07/2019 12:14:49.779672	_send_command                   Ardrone3.Piloting.TakeOff(): has been sent asynchronously
01/07/2019 12:14:49.926993	_recv_cmd_cb                    common.RunState.RunIdChanged(runId='1C613B')
01/07/2019 12:14:59.827051	disconnection                   we are not disconnected yet
01/07/2019 12:14:59.828065	_disconnected_cb                Disconnected from device: ANAFI-0000000
01/07/2019 12:14:59.828758	_disconnection_impl             disconnected from device: b'10.202.0.1'
I arsdkctrl: discovery 'net': remove device name='ANAFI-0000000' id='000000000000000000'
01/07/2019 12:14:59.829649	_device_removed_cb              Device has been removed
I arsdkctrl: discovery 'net': stop
01/07/2019 12:14:59.830431	_stop_discovery                 Discovery has been stopped
01/07/2019 12:14:59.831075	_stop_discovery                 Discovery object has been destroyed
01/07/2019 12:14:59.836237	_stop_discovery                 No discovery instance to be stopped
01/07/2019 12:14:59.839185	_close_stream                   Cannot close stream from State.Created
01/07/2019 12:14:59.878068	disconnection                   Disconnection with the device OK. IP: b'10.202.0.1'
01/07/2019 12:14:59.927127	_stop_discovery                 No discovery instance to be stopped
01/07/2019 12:14:59.930596	_destroy_net_backend            Net backend has been destroyed
01/07/2019 12:14:59.931243	_destroy_manager                Manager has been destroyed
01/07/2019 12:14:59.931945	destroy_timer                   Pomp loop timer has been destroyed
01/07/2019 12:14:59.932566	destroy_timer                   Pomp loop timer has been destroyed
01/07/2019 12:14:59.933130	_destroy_pomp_loop              Pomp loop has been destroyed
```

Thanks,

**Comment by ndessart** [comment]
Before creating an issue here, please have a look at the developer forum. There is much more activity there.

The following topic should answer your question:
https://forum.developer.parrot.com/t/redirecting-olympe-console-output/9219

By default Olympe logs go to the console stdout. To change Olympe log location you must provide a “logfile” parameter to the olympe.Drone constructor.

This parameter defaults to sys.stdout but you can pass any File-object-like object. For example :
```
drone = olympe.Drone("10.202.0.1", logfile=open("/tmp/olympe.log", "a+"))
```
 I am currently considering to redirect log to file by default in a future release.
Please let me know if that works for you.

Thanks

**Comment by shulace13** [comment]
It worked out perfectly! Thank you. And sorry for the inconvenience.

Will close.
